tasks:
  - init: yarn
    command: yarn dev
ports:
  - port: 1234
    onOpen: open-browser

vscode:
  extensions:
    - tombonnike.vscode-status-bar-format-toggle@2.0.0:ZgDPjvnqqBlP/kdKUlJSQA==
    - esbenp.prettier-vscode@6.3.1:iOVHVb01wildbNZ98o51fQ==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==